# Generated by Django 3.1.1 on 2021-09-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210929_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='folder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.folder'),
        ),
    ]
